###GROUP

POST http://localhost:4000/group
Content-Type: application/json

{
  "group_name": "BKL",
  "user_id" : 4,
  "desc": "Maa x"
}

DELETE http://localhost:4000/group/1


### USER

POST http://localhost:4000/user
Content-Type: application/json

{
  "ulid" : "SECRET_KEY",
  "name" : "Krish Poptani",
  "email" : "poptanikrish1@gmail.com",
  "address" : "6 Vikash Path, Alwaar",
  "contact_number" : "52624284287"
}


DELETE http://localhost:4000/user/6

### GROUP USER

POST http://localhost:4000/groupuser
Content-Type: application/json
{
  "group_id" : 34,
  "user_id" : 5
}


DELETE http://localhost:4000/groupuser
Content-Type: application/json
{
  "group_id" : 34,
  "user_id" : 5
}
